import AddIconGif from './add-icon.gif'
import AddIconGif2 from './add-icon2.gif'
import ShopLogo from './ShopLogo.PNG'
import ProfileImage from './profile-img.jpg'
import PhoneIcon from './phone-icon.png'
import PancardIcon from './pancard-icon.png'
import InternetIcon from './internet-icon.png'
import SignitureSampleIcon from './signiture-sample.png'
import  StaffAvtar from './staffAvtar.png'
import TotalWorkIcon from './totalicon.png'
import WorkProcessIcon from './work-process.png'
import CompletedIcon from './complete.png'
import ResignIcon from './resign.png'
export { ShopLogo, ProfileImage, PhoneIcon, PancardIcon, InternetIcon, SignitureSampleIcon, AddIconGif, AddIconGif2, StaffAvtar, TotalWorkIcon, WorkProcessIcon, CompletedIcon, ResignIcon }